export const ARTICLES_REQUEST = 'ARTICLES_REQUEST';
export const ARTICLES_RESPONSE = 'ARTICLES_RESPONSE';
export const ARTICLES_RESPONSE_FAIL = 'ARTICLES_RESPONSE_FAIL';

export const ADD_ARTICLE_REQUEST = 'ADD_ARTICLE_REQUEST';
export const ADD_ARTICLE_RESPONSE = 'ADD_ARTICLE_RESPONSE';
export const ADD_ARTICLE_RESPONSE_FAIL = 'ADD_ARTICLE_RESPONSE_FAIL';

export const UPDATE_ARTICLE_REQUEST = 'UPDATE_ARTICLE_REQUEST';
export const UPDATE_ARTICLE_RESPONSE = 'UPDATE_ARTICLE_RESPONSE';
export const UPDATE_ARTICLE_RESPONSE_FAIL = 'UPDATE_ARTICLE_RESPONSE_FAIL';

export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST';
export const DELETE_ARTICLE_RESPONSE_FAIL = 'DELETE_ARTICLE_RESPONSE_FAIL';
